ARG IMAGE_NAME=registry.access.redhat.com/ubi8/ubi 
ARG IMAGE_TAG=8.10-1132.1733300785
FROM ${IMAGE_NAME}:${IMAGE_TAG}

USER 0

RUN 	yum update -y \ 
&&      yum install -y curl fontconfig \
&&	    yum install -y java-11-openjdk.x86_64
	    
ARG JAVA_INSTALL_ROOT=/usr/lib/jvm/jre-11-openjdk
 
ENV JAVA_HOME=${JAVA_INSTALL_ROOT} \
	PATH=${JAVA_INSTALL_ROOT}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 